remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Welcome to Frederic Wong's Blog!
description: Follow my journey as a software engineer.
navigation:
- title: Home
  url: index.html
- title: About me
  url: about_me.html
linkedin: https://www.linkedin.com/in/frederic-wong
